### ISSUE TITLE
Transition sequentially

### ISSUE THREAD

**Issue by NgKhanh** [joshwcomeau/react-flip-move#112]
Hello, I tried custom EnterAnimation with sequentially properties, mean I want opacity delay until done scaleY transition of item

So I tried this code

```
const customEnterAnimation = {
    from: { transform: 'scaleY(0)' , opacity: '0' },
    to: { transform: 'scaleY(1)', opacity: '1', transition:'transform 0.2s, opacity 0.2s 0.2s' }<---delay until scale done
}
```
But It didnt work, please help

**Comment by joshwcomeau** [comment]
@NgKhanh So, FlipMove doesn't have support for multi-stage animations.

You should just be able to use standard CSS keyframe animations though, at least for enter animations:

```css
@keyframes scaleAndFade {
  0% { transform: scaleY(0); opacity: 0;  }
  50% { transform: scaleY(1); opacity: 0; }
  100% { transform: scaleY(1); opacity: 1; }
}

.your-selector {
  animation: scaleAndFade;
}
```

Hope it helps!
