### ISSUE TITLE
Customize re-order animation

### ISSUE THREAD

**Issue by deibeljc** [joshwcomeau/react-flip-move#127]
I have a use case where I want the re-order animation to behave like such:

when an element wants to move up the list it will essentially animate out (translate up and make opacity 0). When it "reaches" that location it will translate up into the spot and make opacity 1.

Right now the only way I could think to do this was to chain state changes where an item leaves triggering the leaving animation and then enter.

**Comment by joshwcomeau** [comment]
Hm, yeah, that's a tricky one. To be honest, Flip Move wasn't really built to be a flexible, abstract tool; it exists to fluidly move stuff around on a screen when props change.

Thankfully, Flip Move provides escape hatches that _should_ make stuff like this possible. Here's what I've come up with.

### In CSS
I think the way to do this would be to use the `onStart` hook. They're given the direct DOM elements as arguments, so you could apply a class that has the animation you need.

```css
@keyframes stealthFlipMove {
  0% { opacity: 1 }
  25% { opacity: 0 }
  75% { opacity: 0 }
  100% { opacity: 1 }
}

.stealth {
  animation: stealthFlipMove 600ms; /* make this equal to your `duration` */
}
```

```js
<FlipMove
  onStart={(elem, node) => {
    elem.classList.add('stealth');
  }}
```

This isn't a great solution: Unless you're using a CSS-in-JS solution like Aphrodite, you have to hardcode your animation duration in the CSS, which is brittle. Additionally, if your shuffle is interrupted, the animation won't restart, unless you unset and reset the class within that `onStart` callback.


### In JS
An alternative could be to handle the animations from within JS. The [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) has tools to handle interrupts, and could be a great way to accomplish this effect. The downside is it has terrible browser support, so you'd need a polyfill.


Let me know if these solutions are workable. Curious to see the final product if you get it working!
