### ISSUE TITLE
CSS3 Grid

### ISSUE THREAD

**Issue by taylorgoolsby** [joshwcomeau/react-flip-move#249]
Hi,

I know this doesn't work with `display: grid` because of the way it wraps elements, but I was wondering if there are any known alternatives that are similar to react-flip-move, but work with grid?

**Comment by taylorgoolsby** [comment]
nvm, just found https://www.npmjs.com/package/animate-css-grid

**Comment by AlexandraKlein** [comment]
You can target the created div with CSS:

```css
  .container-wrapping-filp-move {
    // Targeting div created by react-flip-move
    > div {
      display: grid;
      grid-gap: 20px;
      grid-template-columns: repeat(3, 1fr);
    }
  }
```
