### ISSUE TITLE
Collapsing margins

### ISSUE THREAD

**Issue by whitegrey** [joshwcomeau/react-flip-move#57]
It seems like flip-move doesn't currently take collapsed margins into account when animating items. This is on 2.4.0-rc2.

**Comment by pvande** [comment]
Also seeing this (or a related) issue.

![image](https://i.gyazo.com/f7c4a4a4bd1c44abcc4ad5b618a3cc7d.gif)

When triggered, the `exit` transition causes each section to jump downwards by about 14px, which happens to be the amount of padding that is applied to the top of each of the bolded headings.

**Comment by joshwcomeau** [comment]
@whitegrey argh, collapsed margins are such a pain. Will add it to the backlog, 

@pvande hmm, very strange. Is this on master or 2.4.0-rc2? Can you share all the relevant CSS (I suspect it's less about the individual items and more about some quirk with the parent and grandparent containers)

**Comment by pvande** [comment]
@joshwcomeau I'm currently running v2.3.0.

Relevant styles:

``` scss
.timeline {
  /* inline */
  position: relative;

  .date-container {
    height: /* inline */;
    margin: 14px 0;

    .day-of-weeks {
      display: block;
      font-size: 14px;
      font-weight: bold;
      line-height: 16px;
    }
  }
}
```
