### ISSUE TITLE
Support appear/mount animation?

### ISSUE THREAD

**Issue by f0rr0** [joshwcomeau/react-flip-move#77]

**Comment by joshwcomeau** [comment]
IMO, this library should do as little as possible; it's not designed to be an all-around animation library, it's just there to handle list re-ordering.

Enter/exit were added by popular demand, and it makes sense to me: that's really just a type of list re-order. For appear, though... there's no re-ordering on mount.

Plus, appear is super simple to do anyway (just use [CSS animation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations)). I don't think it's worth complicating the source for it.

That said, I'm not unswayable. If there are good reasons that I'm not seeing to include appear/mount animations, let me know :)

**Comment by f0rr0** [comment]
That's what I am doing currently, wrapping the children in `CSSTransitionGroup` to animate mount. However, the api does not support complex things like staggering etc. It should not be too complex. The children need to be given a `fadeIn` class after a user specified delay or something. It's aesthetically more pleasing and completes the functionality of this component IMO

**Comment by joshwcomeau** [comment]
I don't think you need CSSTransitionGroup, though. You can just use vanilla CSS animations.

You should even be able to stagger them, by using `nth-child`:

```css
.your-item:nth-child(1) {
  animation: yourAnimation 500ms 0ms;
}

.your-item:nth-child(2) {
  animation: yourAnimation 500ms 20ms;
}

.your-item:nth-child(3) {
  animation: yourAnimation 500ms 40ms;
}
```

This is tedious to do by hand, but simple with a preprocessor like SASS or LESS.

I do see that this would be easier with a simple `appearAnimation` prop, but IMO it's far from the highest priority thing to include, given that I believe it's already pretty straightforward. If you (or someone else) would like to work on it, I'd be happy to review a PR. It would be a bit tricky, though, to make the staggered delays/durations work with it.
